sudo: false

language: php

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

language: php

matrix:
  include:
    - php: 7.2
      env: WP_VERSION=latest ES_VERSION=2.2.0
  fast_finish: true

branches:
  only:
    - master

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle

install:
  - bash bin/install-es.sh $ES_VERSION

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require "phpunit/phpunit=4.8.*|5.7.*"
  - which phpunit
  - phpunit --version
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - curl localhost:9200 && echo "ES is up" || (cat /tmp/elasticsearch.log && exit 1)

script:
  - |
    PHPUNIT_VERSION=$(phpunit --version | egrep -o '[0-9]+\.[0-9]+(\.[0-9]+)?')
    if [[ ${PHPUNIT_VERSION:0:2} != "5." ]]; then
      exit 1
    fi
