language: php

matrix:
  include:
    - php: 7.2
      env: WP_VERSION=latest ES_VERSION=2.2.0
  fast_finish: true

branches:
  only:
    - master

before_install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - curl -O -L https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-$ES_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb
  # - sudo service elasticsearch start
  - composer global require "phpunit/phpunit=4.8.*|5.7.*"
  - which phpunit
  - phpunit --version

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - |
    PHPUNIT_VERSION=$(phpunit --version | egrep -o '[0-9]+\.[0-9]+(\.[0-9]+)?')
    if [[ ${PHPUNIT_VERSION:0:2} != "5." ]]; then
      exit 1
    fi
